POST http://localhost:1337/api/auth/local
Content-Type: application/json

{
    "identifier": "ncbphi001@gmail.com",
    "password": "1234567"
}

###

GET http://localhost:1337/api/users/me
Authorization: 
Content-Type: application/json


###

POST http://localhost:1337/api/auth/local/register
Content-Type: application/json

{
    "username": "philani@faben.uk",
    "email": "philani@faben.uk",
    "password": "1234567"
}
###


POST http://localhost:3000/api/login
Content-Type: application/json

{
  
    "email": "ncbphi001@gmail.com",
    "password": "1234567"
}


###

POST http://localhost:3000/api/register
Content-Type: application/json

{
      "username": "pills",
    "email": "ncbphi005@gmail.com",
    "password": "1234567"
}


###

GET http://localhost:3000/api/products

Content-Type: application/json


###

GET https://api.sendgrid.com/v3/contactdb/custom_fields
On-behalf-of: Philani Ncube
Authorization: Bearer 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



###